### ISSUE TITLE
Big Red

### ISSUE THREAD

**Issue by JustOldWill** [Teo813/Questboard#1]
Big RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig RedBig Red

**Comment by Teo813** [comment]
Banned
