### ISSUE TITLE
BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴

### ISSUE THREAD

**Issue by JustOldWill** [Teo813/Questboard#7]
BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴BigRed🔴

**Comment by Teo813** [comment]
I'm banning you next time
